# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Maniac Lab
description:        Maniac Lab Website.

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://maniaclab.github.io"

# Site logo, image or text
brand:
    image:          maniaclogo.png # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Docs      # if the above "logo:" image variable  is not set, this text logo is displayed instead

brand_2:
    image:          Maniac_Logo2_cropped.svg

# Default author settings
author:
    name:       Jeremy Van
    github:     maniaclab    # Github username for avatar

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jeremy:
        name:       Jeremy Van
        github:     maniaclab    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github:         https://www.github.com/maniaclab
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by <a href="https://github.com/maniaclab">Jeremy Van</a>.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/news/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true
  projects:
    output: true
  collaborations:
    output: true
